[versions]
accompanistPermissions = "0.37.3"
activityKtx = "1.11.0"
androidGradlePlugin = "8.13.1"
androidxComposeBom = "2025.11.00"
appcompat = "1.7.1"
coilCompose = "2.7.0"
junit = "4.13.2"
junitVersion = "1.1.5"
androidxTestRunner = "1.5.2"
koinAndroidxWorkmanager = "4.1.1"
koinBom = "4.1.1"
kotlinVersion = "2.2.21"
kotlinxCoroutinesCore = "1.10.2"
kotlinxSerializationJson = "1.9.0"
kspVersion = "2.1.21-2.0.1"
lifecycleRuntimeCompose = "2.9.4"
lifecycleRuntimeKtx = "2.9.4"
material3 = "1.4.0"
mockk = "1.14.6"
navigationCompose = "2.9.6"
room = "2.8.3"
roomPaging = "2.8.3"
lifecycle = "2.9.4"
foundation = "1.9.4"
navigation3Runtime = "1.0.0-rc01"
pagingCommon = "3.3.6"
workRuntimeKtx = "2.11.0"
roomKtx = "2.8.3"
pagingCompose = "3.3.6"
media3Exoplayer = "1.8.0"
navigation3Ui = "1.0.0-rc01"
media3Ui = "1.8.0"
work-test = "2.7.1"

[libraries]

accompanist-permissions = { module = "com.google.accompanist:accompanist-permissions", version.ref = "accompanistPermissions" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activityKtx" }
androidx-activity-ktx = { module = "androidx.activity:activity-ktx", version.ref = "activityKtx" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
androidx-junit = { module = "androidx.test.ext:junit", version.ref = "junitVersion" }
androidx-lifecycle-runtime-compose = { group = "androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "lifecycleRuntimeCompose" }
androidx-lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-work-runtime-ktx = { group = "androidx.work", name = "work-runtime-ktx", version.ref = "workRuntimeKtx" }
androidx-paging-common = { group = "androidx.paging", name = "paging-common", version.ref = "pagingCommon" }
androidx-paging-compose = { group = "androidx.paging", name = "paging-compose", version.ref = "pagingCompose" }

# media3
media3-exoplayer = { group = "androidx.media3", name = "media3-exoplayer", version.ref = "media3Exoplayer" }
androidx-media3-ui = { group = "androidx.media3", name = "media3-ui", version.ref = "media3Ui" }

# navigation
androidx-navigation3-runtime = { group = "androidx.navigation3", name = "navigation3-runtime", version.ref = "navigation3Runtime" }
androidx-navigation3-ui = { group = "androidx.navigation3", name = "navigation3-ui", version.ref = "navigation3Ui" }
androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigationCompose" }

# material
compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "androidxComposeBom" }
compose-material3 = { module = "androidx.compose.material3:material3", version.ref = "material3" }
compose-ui = { module = "androidx.compose.ui:ui" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
material-icons-extended = { group = "androidx.compose.material", name = "material-icons-extended" }

coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coilCompose" }

# koin
koin-bom = { module = "io.insert-koin:koin-bom", version.ref = "koinBom" }
koin-android = { module = "io.insert-koin:koin-android" }
koin-androidx = { module = "io.insert-koin:koin-androidx-compose" }
koin-androidx-workmanager = { module = "io.insert-koin:koin-androidx-workmanager", version.ref = "koinAndroidxWorkmanager" }
koin-core = { module = "io.insert-koin:koin-core" }

# serialization
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinxCoroutinesCore" }

# room
room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "roomKtx" }
room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
androidx-room-paging = { module = "androidx.room:room-paging", version.ref = "roomPaging" }


# testing
junit = { module = "junit:junit", version.ref = "junit" }
androidx-test-runner = { module = "androidx.test:runner", version.ref = "androidxTestRunner" }
test-mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
work-testing = { module = "androidx.work:work-testing", version.ref = "work-test" }
androidx-lifecycle-process = { group = "androidx.lifecycle", name = "lifecycle-process", version.ref = "lifecycle" }
androidx-foundation = { group = "androidx.compose.foundation", name = "foundation", version.ref = "foundation" }


[plugins]
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
android-library = { id = "com.android.library", version.ref = "androidGradlePlugin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlinVersion" }
kotlinx-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlinVersion" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlinVersion" }
room = { id = "androidx.room", version.ref = "room" }
kotlin-ksp = { id = "com.google.devtools.ksp", version.ref = "kspVersion" }

[bundles]
compose = ["compose-ui",
    "compose-material3",
    "compose-ui-tooling",
    "compose-ui-tooling-preview",
    "material-icons-extended"
]

koin = ["koin-android",
    "koin-androidx",
    "koin-core",
    "koin-androidx-workmanager"
]

room = [
    "room-ktx",
    "room-runtime",
    "androidx-room-paging"
]

navigation = [
    "androidx-navigation3-runtime",
    "androidx-navigation3-ui",
    "androidx-navigation-compose"
]

media3 = [
    "media3-exoplayer",
    "androidx-media3-ui"
]

android-testing = [
    "androidx-junit",
    "androidx-test-runner",
]
testing = ["junit",
    "test-mockk",
    "work-testing",
    "kotlinx-coroutines-test",
]

